name: uniAppBackend
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alsa-lib=1.1.5
  - asn1crypto=1.2.0
  - beautifulsoup4=4.8.2
  - bottle=0.12.17
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - coverage=5.0.3
  - cryptography=2.8
  - dateparser=0.7.2
  - distro=1.4.0
  - feedparser=5.2.1
  - fontconfig=2.13.1
  - freetype=2.10.0
  - giflib=5.2.1
  - icalendar=4.0.4
  - icu=64.2
  - idna=2.8
  - jinja2=2.10.3
  - jpeg=9c
  - lcms2=2.9
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - ncurses=6.1
  - numpy=1.17.3
  - openjdk=11.0.1
  - openssl=1.1.1d
  - pandas=0.25.3
  - pip=19.3.1
  - pthread-stubs=0.4
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.0
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=7.0
  - regex=2020.1.8
  - requests=2.22.0
  - setuptools=42.0.1
  - six=1.13.0
  - soupsieve=1.9.4
  - sqlite=3.30.1
  - tabula-py=1.4.1
  - tk=8.6.8
  - tzlocal=2.0.0
  - urllib3=1.25.7
  - wheel=0.33.6
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yattag=1.12.2
  - zlib=1.2.11
  - zstd=1.4.4

