#!/usr/bin/env bash
# deploy.sh — start, stop, and manage the UniSaarApp server without Docker.
#
# Usage:
#   ./deploy.sh setup          install deps, create .env, check .secrets
#   ./deploy.sh start          start web server + scheduler in background
#   ./deploy.sh stop           stop both processes
#   ./deploy.sh restart        stop then start
#   ./deploy.sh status         show process status and health check
#   ./deploy.sh logs           live-tail web and scheduler logs
#   ./deploy.sh run [job]      run a scraper job now (news/mensa/helpful-numbers/map/all)
#
# Requirements: Python 3.13+, Poetry
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

LOG_DIR="$SCRIPT_DIR/logs"
WEB_PID="$LOG_DIR/web.pid"
SCHED_PID="$LOG_DIR/scheduler.pid"
WEB_LOG="$LOG_DIR/web.log"
SCHED_LOG="$LOG_DIR/scheduler.log"

PORT="${PORT:-$(grep -E '^PORT=' .env 2>/dev/null | cut -d= -f2 || echo 3000)}"

# ── Colours ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
_ok()    { echo -e "${GREEN}✓${NC} $*"; }
_info()  { echo -e "${BOLD}▶${NC} $*"; }
_warn()  { echo -e "${YELLOW}⚠${NC}  $*"; }
_error() { echo -e "${RED}✗${NC} $*" >&2; }

# ── Helpers ───────────────────────────────────────────────────────────────────
_pid_running() {
    local pid_file="$1"
    [[ -f "$pid_file" ]] && kill -0 "$(cat "$pid_file")" 2>/dev/null
}

_stop_one() {
    local name="$1" pid_file="$2"
    if _pid_running "$pid_file"; then
        kill "$(cat "$pid_file")"
        rm -f "$pid_file"
        _ok "stopped $name"
    else
        rm -f "$pid_file" 2>/dev/null || true
        _warn "$name was not running"
    fi
}

# ── setup ─────────────────────────────────────────────────────────────────────
cmd_setup() {
    _info "Checking Python 3.13+..."
    if ! python3 --version 2>&1 | grep -qE "3\.(1[3-9]|[2-9][0-9])"; then
        _error "Python 3.13+ required. Found: $(python3 --version 2>&1)"
        _error "Install via pyenv: https://github.com/pyenv/pyenv"
        exit 1
    fi
    _ok "$(python3 --version)"

    _info "Checking Poetry..."
    if ! command -v poetry &>/dev/null; then
        _error "Poetry not found."
        _error "Install: curl -sSL https://install.python-poetry.org | python3 -"
        exit 1
    fi
    _ok "$(poetry --version)"

    _info "Installing dependencies..."
    poetry install --only main --no-interaction
    _ok "Dependencies installed"

    # .env — create with safe defaults only if missing
    if [[ ! -f .env ]]; then
        _info "Creating .env with defaults..."
        cat > .env << EOF
HOST=0.0.0.0
PORT=3000
LOG_LEVEL=INFO
CACHE_DIR=.cache
NEWS_UPDATE_INTERVAL_MIN=30
MENSA_UPDATE_CRON=0 6 * * *
HELPFUL_NUMBERS_UPDATE_CRON=0 7 * * *
MAP_UPDATE_CRON=0 8 * * *
HTTP_TIMEOUT_SECONDS=30
EOF
        _ok ".env created — edit LOG_LEVEL if needed"
    else
        _ok ".env already exists"
    fi

    # .secrets — must be created manually (never generated by script)
    if [[ ! -f .secrets ]]; then
        _warn ".secrets not found — create it before running start:"
        echo ""
        echo "    cat > .secrets << 'EOF'"
        echo "    MENSA_API_KEY=your-key-here"
        echo "    PROXY_URL=                    # set if server needs a proxy to reach uni-saarland.de"
        echo "    SENTRY_DSN=                   # optional — leave empty to skip error tracking"
        echo "    EOF"
        echo ""
        echo "  MENSA_API_KEY is required. Get it from the Mensaar developer portal."
        echo "  Test direct access: curl -I https://mensaar.de"
        echo "  If that fails, set PROXY_URL to your proxy address."
        exit 1
    else
        _ok ".secrets exists"
    fi

    mkdir -p "$LOG_DIR"
    _ok "Setup complete — run: ./deploy.sh start"
}

# ── start ─────────────────────────────────────────────────────────────────────
_free_port() {
    local pid
    pid="$(lsof -ti :"$PORT" 2>/dev/null || true)"
    if [[ -n "$pid" ]]; then
        _warn "Port $PORT in use by PID $pid — stopping it..."
        kill "$pid" && sleep 1
        _ok "Freed port $PORT"
    fi
}

cmd_start() {
    if [[ ! -f .env ]] || [[ ! -f .secrets ]]; then
        _error "Run ./deploy.sh setup first"
        exit 1
    fi
    mkdir -p "$LOG_DIR"
    _free_port

    # Web server
    if _pid_running "$WEB_PID"; then
        _warn "Web server already running (PID $(cat "$WEB_PID"))"
    else
        nohup poetry run uvicorn src.main:app \
            --host 0.0.0.0 --port "$PORT" --workers 1 \
            >> "$WEB_LOG" 2>&1 &
        echo $! > "$WEB_PID"
        _ok "Web server started — PID $! — port $PORT — log: logs/web.log"
    fi

    # Scheduler (runs cold-start scrape then stays up for scheduled refreshes)
    if _pid_running "$SCHED_PID"; then
        _warn "Scheduler already running (PID $(cat "$SCHED_PID"))"
    else
        nohup poetry run python src/services/scheduler.py \
            >> "$SCHED_LOG" 2>&1 &
        echo $! > "$SCHED_PID"
        _ok "Scheduler started — PID $! — running cold-start scrape — log: logs/scheduler.log"
    fi

    echo ""
    _info "Waiting 8s for cold-start scrape to finish..."
    sleep 8
    cmd_status
}

# ── stop ──────────────────────────────────────────────────────────────────────
cmd_stop() {
    _stop_one "web server" "$WEB_PID"
    _stop_one "scheduler"  "$SCHED_PID"
}

# ── restart ───────────────────────────────────────────────────────────────────
cmd_restart() {
    cmd_stop
    sleep 2
    cmd_start
}

# ── status ────────────────────────────────────────────────────────────────────
cmd_status() {
    echo ""
    echo -e "${BOLD}── Processes ──────────────────────────────────────────${NC}"
    if _pid_running "$WEB_PID"; then
        _ok "web server   running   PID $(cat "$WEB_PID")   port $PORT"
    else
        _error "web server   NOT running"
    fi
    if _pid_running "$SCHED_PID"; then
        _ok "scheduler    running   PID $(cat "$SCHED_PID")"
    else
        _error "scheduler    NOT running"
    fi

    echo ""
    echo -e "${BOLD}── Health ─────────────────────────────────────────────${NC}"
    local health
    if health="$(curl -sf "http://localhost:$PORT/v1/health" 2>/dev/null)"; then
        _ok "health OK — $health"
    else
        _warn "health endpoint not responding yet (try again in a moment)"
    fi
    echo ""
}

# ── logs ──────────────────────────────────────────────────────────────────────
cmd_logs() {
    local files=()
    [[ -f "$SCHED_LOG" ]] && files+=("$SCHED_LOG")
    [[ -f "$WEB_LOG"   ]] && files+=("$WEB_LOG")
    if [[ ${#files[@]} -eq 0 ]]; then
        _warn "No log files yet — run ./deploy.sh start first"
        exit 0
    fi
    exec tail -f "${files[@]}"
}

# ── run ───────────────────────────────────────────────────────────────────────
cmd_run() {
    local job="${1:-all}"
    _info "Running job: $job"
    poetry run manage run "$job"
}

# ── dispatch ──────────────────────────────────────────────────────────────────
case "${1:-help}" in
    setup)   cmd_setup ;;
    start)   cmd_start ;;
    stop)    cmd_stop ;;
    restart) cmd_restart ;;
    status)  cmd_status ;;
    logs)    cmd_logs ;;
    run)     cmd_run "${2:-all}" ;;
    *)
        echo -e "${BOLD}UniSaarApp deploy script${NC}"
        echo ""
        echo "Usage: ./deploy.sh <command>"
        echo ""
        echo "  setup           install deps, create .env, verify .secrets"
        echo "  start           start web server + scheduler in background"
        echo "  stop            stop both processes"
        echo "  restart         stop then start"
        echo "  status          show process status and health check"
        echo "  logs            live-tail web and scheduler logs"
        echo "  run [job]       run a scraper job now"
        echo "                  jobs: news | mensa | helpful-numbers | map | all"
        echo ""
        echo "First-time setup on a new host:"
        echo "  git checkout upgrade/modern-python-server"
        echo "  ./deploy.sh setup"
        echo "  # create .secrets as prompted, then:"
        echo "  ./deploy.sh start"
        ;;
esac
